run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - ineffassign
    - gofmt
    - goimports
    - misspell
    - revive
  disable:
    - govet
    - staticcheck
    - gosimple
    - typecheck
    - gocritic
